name: object_editor
description: A no-code UI  class editor for dart using macros and mirrors
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  macro_builder:
    git:
      url: https://github.com/jakemac53/macro_prototype.git
      ref: main
  build_runner: ^2.1.0



flutter:
  uses-material-design: true
